# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Mantra Yatra"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/mantrayatra/hugo-mantra-yatra/master/LICENSE.md"
description = "Theme used for https://mantrayatra.com"
homepage = "https://github.com/mantrayatra/hugo-mantra-yatra/"
tags = ["", ""]
features = ["", ""]
min_version = 0.20.1

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
